/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CompanyInput = IDL.Record({
  'yearsActive' : IDL.Nat,
  'employees' : IDL.Nat,
  'websiteUrl' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'countries' : IDL.Nat,
  'logoUrl' : ExternalBlob,
  'industry' : IDL.Text,
});
export const CompanyId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Company = IDL.Record({
  'id' : CompanyId,
  'yearsActive' : IDL.Nat,
  'employees' : IDL.Nat,
  'websiteUrl' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'countries' : IDL.Nat,
  'logoUrl' : ExternalBlob,
  'industry' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ValueItem = IDL.Record({
  'title' : IDL.Text,
  'icon' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const TimelineItem = IDL.Record({
  'title' : IDL.Text,
  'year' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const AboutContent = IDL.Record({
  'missionText' : IDL.Text,
  'values' : IDL.Vec(ValueItem),
  'visionText' : IDL.Text,
  'timeline' : IDL.Vec(TimelineItem),
});
export const AdminProfile = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'joinedAt' : IDL.Int,
  'role' : IDL.Text,
  'photoUrl' : IDL.Text,
  'principalId' : IDL.Text,
});
export const User = IDL.Record({
  'displayName' : IDL.Text,
  'registeredAt' : IDL.Int,
  'principalId' : IDL.Text,
});
export const Analytics = IDL.Record({
  'totalEmployees' : IDL.Nat,
  'maxYearsActive' : IDL.Nat,
  'companyCount' : IDL.Nat,
  'totalCountries' : IDL.Nat,
});
export const ContactInfo = IDL.Record({
  'twitterUrl' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'mapUrl' : IDL.Text,
  'phone' : IDL.Text,
  'facebookUrl' : IDL.Text,
  'linkedinUrl' : IDL.Text,
});
export const ContactId = IDL.Nat;
export const ContactSubmission = IDL.Record({
  'id' : ContactId,
  'name' : IDL.Text,
  'submittedAt' : Timestamp,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const HomeContent = IDL.Record({
  'stat4Value' : IDL.Text,
  'button1Label' : IDL.Text,
  'stat1Label' : IDL.Text,
  'stat2Value' : IDL.Text,
  'stat4Label' : IDL.Text,
  'heroBadge' : IDL.Text,
  'heroSubtitle' : IDL.Text,
  'button2Label' : IDL.Text,
  'stat2Label' : IDL.Text,
  'stat3Value' : IDL.Text,
  'heroTitle' : IDL.Text,
  'stat1Value' : IDL.Text,
  'stat3Label' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addCompany' : IDL.Func([CompanyInput], [Company], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCompany' : IDL.Func([CompanyId], [IDL.Bool], []),
  'getAboutContent' : IDL.Func([], [AboutContent], ['query']),
  'getAdminProfile' : IDL.Func([], [IDL.Opt(AdminProfile)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getAnalytics' : IDL.Func([], [Analytics], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompanies' : IDL.Func([], [IDL.Vec(Company)], ['query']),
  'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getHomeContent' : IDL.Func([], [HomeContent], ['query']),
  'getUser' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([], [User], []),
  'submitContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [ContactSubmission],
      [],
    ),
  'updateAboutContent' : IDL.Func([AboutContent], [IDL.Bool], []),
  'updateCompany' : IDL.Func([CompanyId, CompanyInput], [IDL.Bool], []),
  'updateContactInfo' : IDL.Func([ContactInfo], [IDL.Bool], []),
  'updateHomeContent' : IDL.Func([HomeContent], [IDL.Bool], []),
  'updateUserDisplayName' : IDL.Func([IDL.Text], [User], []),
  'upsertAdminProfile' : IDL.Func([AdminProfile], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CompanyInput = IDL.Record({
    'yearsActive' : IDL.Nat,
    'employees' : IDL.Nat,
    'websiteUrl' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'countries' : IDL.Nat,
    'logoUrl' : ExternalBlob,
    'industry' : IDL.Text,
  });
  const CompanyId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Company = IDL.Record({
    'id' : CompanyId,
    'yearsActive' : IDL.Nat,
    'employees' : IDL.Nat,
    'websiteUrl' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'countries' : IDL.Nat,
    'logoUrl' : ExternalBlob,
    'industry' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ValueItem = IDL.Record({
    'title' : IDL.Text,
    'icon' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const TimelineItem = IDL.Record({
    'title' : IDL.Text,
    'year' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const AboutContent = IDL.Record({
    'missionText' : IDL.Text,
    'values' : IDL.Vec(ValueItem),
    'visionText' : IDL.Text,
    'timeline' : IDL.Vec(TimelineItem),
  });
  const AdminProfile = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'joinedAt' : IDL.Int,
    'role' : IDL.Text,
    'photoUrl' : IDL.Text,
    'principalId' : IDL.Text,
  });
  const User = IDL.Record({
    'displayName' : IDL.Text,
    'registeredAt' : IDL.Int,
    'principalId' : IDL.Text,
  });
  const Analytics = IDL.Record({
    'totalEmployees' : IDL.Nat,
    'maxYearsActive' : IDL.Nat,
    'companyCount' : IDL.Nat,
    'totalCountries' : IDL.Nat,
  });
  const ContactInfo = IDL.Record({
    'twitterUrl' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'mapUrl' : IDL.Text,
    'phone' : IDL.Text,
    'facebookUrl' : IDL.Text,
    'linkedinUrl' : IDL.Text,
  });
  const ContactId = IDL.Nat;
  const ContactSubmission = IDL.Record({
    'id' : ContactId,
    'name' : IDL.Text,
    'submittedAt' : Timestamp,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const HomeContent = IDL.Record({
    'stat4Value' : IDL.Text,
    'button1Label' : IDL.Text,
    'stat1Label' : IDL.Text,
    'stat2Value' : IDL.Text,
    'stat4Label' : IDL.Text,
    'heroBadge' : IDL.Text,
    'heroSubtitle' : IDL.Text,
    'button2Label' : IDL.Text,
    'stat2Label' : IDL.Text,
    'stat3Value' : IDL.Text,
    'heroTitle' : IDL.Text,
    'stat1Value' : IDL.Text,
    'stat3Label' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addCompany' : IDL.Func([CompanyInput], [Company], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCompany' : IDL.Func([CompanyId], [IDL.Bool], []),
    'getAboutContent' : IDL.Func([], [AboutContent], ['query']),
    'getAdminProfile' : IDL.Func([], [IDL.Opt(AdminProfile)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getAnalytics' : IDL.Func([], [Analytics], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompanies' : IDL.Func([], [IDL.Vec(Company)], ['query']),
    'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getHomeContent' : IDL.Func([], [HomeContent], ['query']),
    'getUser' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([], [User], []),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [ContactSubmission],
        [],
      ),
    'updateAboutContent' : IDL.Func([AboutContent], [IDL.Bool], []),
    'updateCompany' : IDL.Func([CompanyId, CompanyInput], [IDL.Bool], []),
    'updateContactInfo' : IDL.Func([ContactInfo], [IDL.Bool], []),
    'updateHomeContent' : IDL.Func([HomeContent], [IDL.Bool], []),
    'updateUserDisplayName' : IDL.Func([IDL.Text], [User], []),
    'upsertAdminProfile' : IDL.Func([AdminProfile], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };