/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AboutContent {
  'missionText' : string,
  'values' : Array<ValueItem>,
  'visionText' : string,
  'timeline' : Array<TimelineItem>,
}
export interface AdminProfile {
  'bio' : string,
  'name' : string,
  'joinedAt' : bigint,
  'role' : string,
  'photoUrl' : string,
  'principalId' : string,
}
export interface Analytics {
  'totalEmployees' : bigint,
  'maxYearsActive' : bigint,
  'companyCount' : bigint,
  'totalCountries' : bigint,
}
export interface Company {
  'id' : CompanyId,
  'yearsActive' : bigint,
  'employees' : bigint,
  'websiteUrl' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'isActive' : boolean,
  'countries' : bigint,
  'logoUrl' : ExternalBlob,
  'industry' : string,
}
export type CompanyId = bigint;
export interface CompanyInput {
  'yearsActive' : bigint,
  'employees' : bigint,
  'websiteUrl' : string,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'countries' : bigint,
  'logoUrl' : ExternalBlob,
  'industry' : string,
}
export type ContactId = bigint;
export interface ContactInfo {
  'twitterUrl' : string,
  'email' : string,
  'address' : string,
  'mapUrl' : string,
  'phone' : string,
  'facebookUrl' : string,
  'linkedinUrl' : string,
}
export interface ContactSubmission {
  'id' : ContactId,
  'name' : string,
  'submittedAt' : Timestamp,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export interface HomeContent {
  'stat4Value' : string,
  'button1Label' : string,
  'stat1Label' : string,
  'stat2Value' : string,
  'stat4Label' : string,
  'heroBadge' : string,
  'heroSubtitle' : string,
  'button2Label' : string,
  'stat2Label' : string,
  'stat3Value' : string,
  'heroTitle' : string,
  'stat1Value' : string,
  'stat3Label' : string,
}
export interface TimelineItem {
  'title' : string,
  'year' : string,
  'description' : string,
  'imageUrl' : string,
}
export type Timestamp = bigint;
export interface User {
  'displayName' : string,
  'registeredAt' : bigint,
  'principalId' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface ValueItem {
  'title' : string,
  'icon' : string,
  'description' : string,
  'imageUrl' : string,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addCompany' : ActorMethod<[CompanyInput], Company>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCompany' : ActorMethod<[CompanyId], boolean>,
  'getAboutContent' : ActorMethod<[], AboutContent>,
  'getAdminProfile' : ActorMethod<[], [] | [AdminProfile]>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getAnalytics' : ActorMethod<[], Analytics>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompanies' : ActorMethod<[], Array<Company>>,
  'getContactInfo' : ActorMethod<[], ContactInfo>,
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getHomeContent' : ActorMethod<[], HomeContent>,
  'getUser' : ActorMethod<[], [] | [User]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<[], User>,
  'submitContact' : ActorMethod<
    [string, string, string, string],
    ContactSubmission
  >,
  'updateAboutContent' : ActorMethod<[AboutContent], boolean>,
  'updateCompany' : ActorMethod<[CompanyId, CompanyInput], boolean>,
  'updateContactInfo' : ActorMethod<[ContactInfo], boolean>,
  'updateHomeContent' : ActorMethod<[HomeContent], boolean>,
  'updateUserDisplayName' : ActorMethod<[string], User>,
  'upsertAdminProfile' : ActorMethod<[AdminProfile], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];